### ISSUE TITLE
Hello, and how can I help?

### ISSUE THREAD

**Issue by mcanthony** [circuitsim/circuit-simulator#29]
I see your in the beginning phases of this project and there is not much to see, but what I do see I like. This is the most active and current effort to create such a thing on the web so I thought this is where I would like to offer my help. When I first started programming many years ago I dreamed that one day I could create something like this. It seemed like a very far off goal, one I had l had long since forgotten about until recently while getting deep into DSP/Audio programming on the web.

One of my goals is to be able to emulate analog circuits which will produce a signal you can hear and interact with as well as visualize.

Where are you at with this project and where could you use the most input and/or assistance?

**Comment by ThomWright** [comment]
Hi @mcanthony, thanks for getting in touch!

I did my degree in Electronic Engineering with Music Tech. Systems, so audio electronics (especially guitar amps/effects) is an interest of mine too.

Like you say, this project is fairly young so there's lots to do. What's your background/interests programming-wise? You sound like you might enjoy working on the simulation stuff, rather than the UI? There's not much of a to-do list at the moment, but we could create a bunch of issues for stuff you might be interested in.

Have you played around with [the Falstad simulator](http://falstad.com/circuit/) at all? Most of my inspiration comes from that since I did some work on it for a uni project. You can find the source [here](https://github.com/hausen/circuit-simulator).

BTW I'm about to start a new job so my contributions might ramp down a bit. It would be great to have someone to work with though :smiley:
